// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApDfqXGKYI-ygwvH6LrAUeI7NisOgCXPA',
    appId: '1:589103100533:web:6bdba3363502fe4b703e3c',
    messagingSenderId: '589103100533',
    projectId: 'ecom-manager-80fcc',
    authDomain: 'ecom-manager-80fcc.firebaseapp.com',
    storageBucket: 'ecom-manager-80fcc.firebasestorage.app',
    measurementId: 'G-1966XL6V7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg9OyFp4pfzlqCODdyu4wE5Yq3Sk1pvy8',
    appId: '1:589103100533:android:881dffe15966ce53703e3c',
    messagingSenderId: '589103100533',
    projectId: 'ecom-manager-80fcc',
    storageBucket: 'ecom-manager-80fcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcE2QoxnhHzs9WyplHtcPjLz5Nl3YRnzk',
    appId: '1:589103100533:ios:87a0361c8539dc28703e3c',
    messagingSenderId: '589103100533',
    projectId: 'ecom-manager-80fcc',
    storageBucket: 'ecom-manager-80fcc.firebasestorage.app',
    iosBundleId: 'com.example.ecomManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcE2QoxnhHzs9WyplHtcPjLz5Nl3YRnzk',
    appId: '1:589103100533:ios:87a0361c8539dc28703e3c',
    messagingSenderId: '589103100533',
    projectId: 'ecom-manager-80fcc',
    storageBucket: 'ecom-manager-80fcc.firebasestorage.app',
    iosBundleId: 'com.example.ecomManager',
  );
}
